name: 'Summarize PR'
description: 'A simple GitHub action that can create a brief information about commits in a pull request(PR).'
branding:
  icon: file-text
  color: purple
runs:
  using: 'docker'
  image: 'Dockerfile'
